import type { ChordDefinition } from '@/lib/theory/definitions/types';

/**
 * Canonical chord catalog. `symbol` is the legacy `suffix` used in ChordEvent.
 * Intervals are the sole source for MIDI pitch-class sets (voicing may choose register).
 */
export const CHORD_CATALOG: ChordDefinition[] = [
  // —— Triads ——
  {
    id: 'major',
    symbol: '',
    buttonLabel: 'maj',
    quality: 'major',
    intervals: [0, 4, 7],
    extensions: [],
    alterations: [],
    degree: null,
    category: 'triad',
    priority: 10,
    tags: ['pop', 'free'],
  },
  {
    id: 'minor',
    symbol: 'm',
    buttonLabel: 'm',
    quality: 'minor',
    intervals: [0, 3, 7],
    extensions: [],
    alterations: [],
    degree: null,
    category: 'triad',
    priority: 11,
    tags: ['pop', 'free'],
  },
  {
    id: 'dim',
    symbol: 'dim',
    buttonLabel: 'dim',
    quality: 'diminished',
    intervals: [0, 3, 6],
    extensions: [],
    alterations: [],
    degree: 'vii°',
    category: 'triad',
    priority: 12,
    tags: ['pop', 'free'],
  },
  {
    id: 'aug',
    symbol: 'aug',
    buttonLabel: 'aug',
    quality: 'augmented',
    intervals: [0, 4, 8],
    extensions: [],
    alterations: [],
    degree: null,
    category: 'triad',
    priority: 13,
    tags: ['jazz'],
  },

  // —— Sevenths (separate tab) ——
  {
    id: 'maj7',
    symbol: 'maj7',
    buttonLabel: 'maj7',
    quality: 'major',
    intervals: [0, 4, 7, 11],
    extensions: [],
    alterations: [],
    degree: ['I', 'IV'],
    category: 'seventh',
    priority: 20,
    tags: ['pop', 'free'],
  },
  {
    id: 'm7',
    symbol: 'm7',
    buttonLabel: 'm7',
    quality: 'minor',
    intervals: [0, 3, 7, 10],
    extensions: [],
    alterations: [],
    degree: ['ii', 'iii', 'vi'],
    category: 'seventh',
    priority: 21,
    tags: ['pop', 'free'],
  },
  {
    id: 'dom7',
    symbol: '7',
    buttonLabel: '7',
    quality: 'dominant',
    intervals: [0, 4, 7, 10],
    extensions: [],
    alterations: [],
    degree: 'V',
    category: 'seventh',
    priority: 22,
    tags: ['pop', 'free'],
  },
  {
    id: 'm7b5',
    symbol: 'm7♭5',
    buttonLabel: 'm7♭5',
    quality: 'halfDim',
    intervals: [0, 3, 6, 10],
    extensions: [],
    alterations: ['b5'],
    degree: 'vii°',
    category: 'seventh',
    priority: 23,
    tags: ['pop', 'free'],
  },
  {
    id: 'dim7',
    symbol: 'dim7',
    buttonLabel: 'dim7',
    quality: 'diminished',
    intervals: [0, 3, 6, 9],
    extensions: [],
    alterations: [],
    degree: 'vii°',
    category: 'seventh',
    priority: 24,
    tags: ['jazz', 'pro'],
  },

  // —— Suspended / add / sixth ——
  {
    id: 'sus2',
    symbol: 'sus2',
    buttonLabel: 'sus2',
    quality: 'suspended',
    intervals: [0, 2, 7],
    extensions: [],
    alterations: [],
    degree: null,
    category: 'tension',
    priority: 30,
    tags: ['pop', 'pro'],
  },
  {
    id: 'sus4',
    symbol: 'sus4',
    buttonLabel: 'sus4',
    quality: 'suspended',
    intervals: [0, 5, 7],
    extensions: [],
    alterations: [],
    degree: null,
    category: 'tension',
    priority: 31,
    tags: ['pop', 'free'],
  },
  {
    id: '6',
    symbol: '6',
    buttonLabel: '6th',
    quality: 'major',
    intervals: [0, 4, 7, 9],
    extensions: ['6'],
    alterations: [],
    degree: ['I', 'IV', 'V'],
    category: 'tension',
    priority: 32,
    tags: ['pop', 'pro'],
  },
  {
    id: 'm6',
    symbol: 'm6',
    buttonLabel: 'm6',
    quality: 'minor',
    intervals: [0, 3, 7, 9],
    extensions: ['6'],
    alterations: [],
    degree: 'ii',
    category: 'tension',
    priority: 33,
    tags: ['pop', 'pro'],
  },
  {
    id: 'add9',
    symbol: 'add9',
    buttonLabel: 'add9',
    quality: 'major',
    intervals: [0, 4, 7, 14],
    extensions: ['9'],
    alterations: [],
    degree: ['I', 'IV', 'V'],
    category: 'tension',
    priority: 34,
    tags: ['pop', 'free'],
  },
  {
    id: 'm_add9',
    symbol: 'm(add9)',
    buttonLabel: 'add9',
    quality: 'minor',
    intervals: [0, 3, 7, 14],
    extensions: ['9'],
    alterations: [],
    // iii is excluded from every ♮9 form: its 9th is the Phrygian ♭2's neighbour
    // (F# over E in C) and leaves the key. iii takes ♭9 instead.
    degree: ['ii', 'vi'],
    category: 'tension',
    priority: 35,
    tags: ['pop', 'free'],
  },
  {
    id: 'm_add11',
    symbol: 'm(add11)',
    buttonLabel: '11',
    quality: 'minor',
    intervals: [0, 3, 7, 17],
    extensions: ['11'],
    alterations: [],
    degree: 'iii',
    category: 'tension',
    priority: 36,
    tags: ['pop', 'pro'],
  },

  // —— Ninth / eleventh / thirteenth ——
  {
    id: 'dom9',
    symbol: '9',
    buttonLabel: '9',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 14],
    extensions: ['9'],
    alterations: [],
    degree: 'V',
    category: 'tension',
    priority: 40,
    tags: ['pop', 'pro'],
  },
  {
    id: 'maj9',
    symbol: 'maj9',
    buttonLabel: '9',
    quality: 'major',
    intervals: [0, 4, 7, 11, 14],
    extensions: ['9'],
    alterations: [],
    degree: ['I', 'IV'],
    category: 'tension',
    priority: 41,
    tags: ['pop', 'pro'],
  },
  {
    id: 'm9',
    symbol: 'm9',
    buttonLabel: '9',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 14],
    extensions: ['9'],
    alterations: [],
    degree: ['ii', 'vi'],
    category: 'tension',
    priority: 42,
    tags: ['pop', 'pro'],
  },
  {
    id: 'dom11',
    symbol: '11',
    buttonLabel: '11',
    quality: 'dominant',
    intervals: [0, 5, 7, 10, 14],
    extensions: ['9', '11'],
    alterations: [],
    degree: 'V',
    category: 'tension',
    priority: 43,
    tags: ['pop', 'jazz', 'pro'],
  },
  {
    id: 'maj11',
    symbol: 'maj11',
    buttonLabel: 'maj11',
    quality: 'major',
    intervals: [0, 4, 7, 11, 14, 17],
    extensions: ['9', '11'],
    alterations: [],
    // No degree offers it: over I the ♮11 is the avoid note against the major 3rd,
    // and over IV it would need a ♭7 of the key (B♭ in C). Kept for legacy spelling.
    degree: null,
    category: 'tension',
    priority: 44,
    tags: ['pop', 'jazz', 'pro'],
  },
  {
    id: 'm11',
    symbol: 'm11',
    buttonLabel: '11',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 14, 17],
    extensions: ['9', '11'],
    alterations: [],
    degree: ['ii', 'vi'],
    category: 'tension',
    priority: 45,
    tags: ['pop', 'pro'],
  },
  {
    id: 'dom13',
    symbol: '13',
    buttonLabel: '13',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 14, 21],
    extensions: ['9', '13'],
    alterations: [],
    degree: 'V',
    category: 'tension',
    priority: 46,
    tags: ['pop', 'pro'],
  },
  {
    id: 'maj13',
    symbol: 'maj13',
    buttonLabel: '13',
    quality: 'major',
    intervals: [0, 4, 7, 11, 14, 21],
    extensions: ['9', '13'],
    alterations: [],
    degree: ['I', 'IV'],
    category: 'tension',
    priority: 47,
    tags: ['pop', 'pro'],
  },
  {
    id: 'm13',
    symbol: 'm13',
    buttonLabel: '13',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 14, 21],
    extensions: ['9', '13'],
    alterations: [],
    // ii only: the ♮13 is Dorian's defining note, but over vi it is the raised 6th
    // of the key (F# in C). vi takes ♭13 instead.
    degree: 'ii',
    category: 'tension',
    priority: 48,
    tags: ['pop', 'jazz', 'pro'],
  },

  // —— Phase 5 extensions ——
  {
    id: 'six_nine',
    symbol: '6/9',
    buttonLabel: '6/9',
    quality: 'major',
    intervals: [0, 4, 7, 9, 14],
    extensions: ['6', '9'],
    alterations: [],
    degree: ['I', 'IV'],
    category: 'tension',
    priority: 50,
    tags: ['pop', 'pro'],
  },
  {
    id: 'm6_nine',
    symbol: 'm6/9',
    buttonLabel: '6/9',
    quality: 'minor',
    intervals: [0, 3, 7, 9, 14],
    extensions: ['6', '9'],
    alterations: [],
    degree: 'ii',
    category: 'tension',
    priority: 51,
    tags: ['pop', 'pro'],
  },
  {
    id: 'maj9_sharp11',
    symbol: 'maj9(#11)',
    buttonLabel: 'maj9(#11)',
    quality: 'major',
    intervals: [0, 4, 7, 11, 14, 18],
    extensions: ['9'],
    alterations: ['#11'],
    degree: ['I', 'IV'],
    category: 'tension',
    priority: 52,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'maj13_sharp11',
    symbol: 'maj13(#11)',
    buttonLabel: 'maj13(#11)',
    quality: 'major',
    intervals: [0, 4, 7, 11, 14, 18, 21],
    extensions: ['9', '13'],
    alterations: ['#11'],
    degree: ['I', 'IV'],
    category: 'tension',
    priority: 53,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'm9_11',
    symbol: 'm9(11)',
    buttonLabel: '9(11)',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 14, 17],
    extensions: ['9', '11'],
    alterations: [],
    degree: ['ii', 'vi'],
    category: 'tension',
    priority: 54,
    tags: ['pop', 'jazz', 'pro'],
  },
  {
    id: 'm13_9',
    symbol: 'm13(9)',
    buttonLabel: '13(9)',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 14, 21],
    extensions: ['9', '13'],
    alterations: [],
    degree: 'ii',
    category: 'tension',
    priority: 55,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'm13_9_11',
    symbol: 'm13(9,11)',
    buttonLabel: 'm13(9,11)',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 14, 17, 21],
    extensions: ['9', '11', '13'],
    alterations: [],
    degree: 'ii',
    category: 'tension',
    priority: 56,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom13_sharp11',
    symbol: '13(#11)',
    buttonLabel: '13(#11)',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 14, 18, 21],
    extensions: ['9', '13'],
    alterations: ['#11'],
    degree: 'V',
    category: 'tension',
    priority: 57,
    tags: ['jazz', 'pro'],
  },

  // —— Altered dominants (V) ——
  {
    id: 'dom7_b9',
    symbol: '7(♭9)',
    buttonLabel: '♭9',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 13],
    extensions: [],
    alterations: ['b9'],
    degree: 'V',
    category: 'altered',
    priority: 60,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom7_sharp9',
    symbol: '7(#9)',
    buttonLabel: '♯9',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 15],
    extensions: [],
    alterations: ['#9'],
    degree: 'V',
    category: 'altered',
    priority: 61,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom7_sharp11',
    symbol: '7(#11)',
    buttonLabel: '♯11',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 18],
    extensions: [],
    alterations: ['#11'],
    degree: 'V',
    category: 'altered',
    priority: 62,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom7_b13',
    symbol: '7(♭13)',
    buttonLabel: '♭13',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 20],
    extensions: [],
    alterations: ['b13'],
    degree: 'V',
    category: 'altered',
    priority: 63,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom7_b9_b13',
    symbol: '7(♭9,♭13)',
    buttonLabel: '♭9♭13',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 13, 20],
    extensions: [],
    alterations: ['b9', 'b13'],
    degree: 'V',
    category: 'altered',
    priority: 64,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom7_sharp9_b13',
    symbol: '7(#9,♭13)',
    buttonLabel: '♯9♭13',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 15, 20],
    extensions: [],
    alterations: ['#9', 'b13'],
    degree: 'V',
    category: 'altered',
    priority: 65,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom13_b9',
    symbol: '13(♭9)',
    buttonLabel: '13(♭9)',
    quality: 'dominant',
    intervals: [0, 4, 7, 10, 13, 21],
    extensions: ['13'],
    alterations: ['b9'],
    degree: 'V',
    category: 'altered',
    priority: 66,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dom7alt',
    symbol: '7alt',
    buttonLabel: 'alt',
    quality: 'dominant',
    intervals: [0, 4, 10, 13, 15, 18, 20],
    extensions: [],
    alterations: ['b9', '#9', '#11', 'b13'],
    degree: 'V',
    category: 'altered',
    priority: 67,
    tags: ['jazz', 'pro'],
  },

  // —— Altered minor colours (iii / vi) ——
  // Both tones are inside the major scale but sit a semitone above a chord tone,
  // so classic theory files them as altered rather than as plain tensions.
  {
    id: 'm7_b9',
    symbol: 'm7(♭9)',
    buttonLabel: '♭9',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 13],
    extensions: [],
    alterations: ['b9'],
    degree: 'iii',
    category: 'altered',
    priority: 68,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'm7_b13',
    symbol: 'm7(♭13)',
    buttonLabel: '♭13',
    quality: 'minor',
    intervals: [0, 3, 7, 10, 20],
    extensions: [],
    alterations: ['b13'],
    degree: 'vi',
    category: 'altered',
    priority: 69,
    tags: ['jazz', 'pro'],
  },

  // —— vii° tensions ——
  {
    id: 'm7b5_9',
    symbol: 'm7♭5(9)',
    buttonLabel: 'm7♭5(9)',
    quality: 'halfDim',
    intervals: [0, 3, 6, 10, 14],
    extensions: ['9'],
    alterations: ['b5'],
    // Not vii° in a major key: the ♮9 over the leading tone is out of key (C# over
    // B in C). Locrian's 2nd is flat, so vii° takes m7♭5(♭9) — see the altered set.
    degree: null,
    category: 'tension',
    priority: 70,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'm7b5_11',
    symbol: 'm7♭5(11)',
    buttonLabel: 'm7♭5(11)',
    quality: 'halfDim',
    intervals: [0, 3, 6, 10, 17],
    extensions: ['11'],
    alterations: ['b5'],
    degree: 'vii°',
    category: 'tension',
    priority: 71,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'm7b5_b13',
    symbol: 'm7♭5(♭13)',
    buttonLabel: 'm7♭5(♭13)',
    quality: 'halfDim',
    intervals: [0, 3, 6, 10, 20],
    extensions: [],
    alterations: ['b5', 'b13'],
    degree: 'vii°',
    category: 'tension',
    priority: 72,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'm7b5_b9',
    symbol: 'm7♭5(♭9)',
    buttonLabel: '♭9',
    quality: 'halfDim',
    intervals: [0, 3, 6, 10, 13],
    extensions: [],
    alterations: ['b5', 'b9'],
    degree: 'vii°',
    category: 'altered',
    priority: 74,
    tags: ['jazz', 'pro'],
  },
  {
    id: 'dim7_add9',
    symbol: 'dim7(add9)',
    buttonLabel: 'dim7(add9)',
    quality: 'diminished',
    intervals: [0, 3, 6, 9, 14],
    extensions: ['9'],
    alterations: [],
    degree: 'vii°',
    category: 'tension',
    priority: 73,
    tags: ['jazz', 'pro'],
  },
];

const bySymbol = new Map<string, ChordDefinition>(CHORD_CATALOG.map((d) => [d.symbol, d]));
const byId = new Map<string, ChordDefinition>(CHORD_CATALOG.map((d) => [d.id, d]));

export function getDefinitionBySymbol(symbol: string): ChordDefinition | undefined {
  return bySymbol.get(symbol);
}

export function getDefinitionById(id: string): ChordDefinition | undefined {
  return byId.get(id);
}

/** Intervals for a legacy suffix/symbol; unknown → major triad (compat). */
export function intervalsForSuffix(suffix: string): readonly number[] {
  return bySymbol.get(suffix)?.intervals ?? bySymbol.get('')!.intervals;
}

export function pitchClassesFromIntervals(intervals: readonly number[]): number[] {
  const set = new Set(intervals.map((n) => ((n % 12) + 12) % 12));
  return [...set].sort((a, b) => a - b);
}
