export const GROOVE_FEATURE_SCHEMA = {
  version: 1,
  unit: 'beat unless noted',
  fields: {
    attackGroupsPerBar: 'Mean simultaneous attack groups per bar.',
    attackDensity: 'Attack groups divided by total beats.',
    restRatio: 'Unoccupied 1/16 grid slots divided by all slots.',
    beatPositionHistogram: 'Normalized 16-bin attack histogram within a 4/4 bar.',
    offBeatRatio: 'Attack groups not placed on an integer beat.',
    syncopation: 'Attack groups on eighth offbeats or finer positions.',
    ioiDistribution: 'Raw and summary inter-onset intervals between attack groups.',
    ioiVariation: 'IOI standard deviation divided by IOI mean.',
    gridDeviationMean: 'Mean absolute deviation from nearest eighth-note grid.',
    gridDeviationStd: 'Standard deviation of signed eighth-grid deviations.',
    gridDeviationPattern: 'Signed eighth-grid deviation for every attack group.',
    velocityMean: 'Mean note velocity.',
    velocityStd: 'Population standard deviation of note velocity.',
    velocityRange: 'Maximum minus minimum note velocity.',
    velocityContour: 'Mean velocity of each attack group in time order.',
    accentPositions: 'Beat-in-bar positions at or above the 75th velocity percentile.',
    timingVelocityCorrelation: 'Pearson correlation of metric beat strength and group velocity.',
    durationMedian: 'Median note duration.',
    articulationRatio: 'Median duration divided by time to the next attack.',
    cc64Coverage: 'Fraction of total beats for which CC64 is down.',
    phraseRepetitionSimilarity:
      'Cosine similarity of velocity-weighted 1/16 attack grids, bars 1–4 vs 5–8.',
    phraseVariationAmount: 'One minus phraseRepetitionSimilarity.',
  },
} as const;
